### ISSUE TITLE
[Solved] double `?` mark when redirecting snappay

### ISSUE THREAD

**Issue by muhammad-ihsan** [veritrans/SNAP-Prestashop#6]
I have following the instruction and my own redirect like this:
`http://[your-url]/index.php?fc=module&module=midtranspay&controller=success?&order_id=24&status_code=200&transaction_status=capture`

As we can see the question mark (?) is showing `index.php?` and `success?` so the result is not going to the right page. (404 page)

Regards,
Ihsan ❤️ midtrans

**Comment by rizdaprasetya** [comment]
Hi @muhammad-ihsan 

Thanks for reporting.
Do you have your prestashop hosted? please share link so that I can try to take a look at your prestashop payment page. Because I'm unable to get the same issue when I tried on my setup.

The way we try to handle double `?` is by using this javascript piece:
https://github.com/veritrans/SNAP-Prestashop/blob/master/views/templates/front/snappay.tpl#L114

But looks like it doesn't work on your setup. I'll need to take a look.

Thanks.

**Comment by muhammad-ihsan** [comment]
aahh....I already change it use vt-web prestashop. But i curious and try to take a look into the project too, and found this [https://github.com/veritrans/SNAP-Prestashop/blob/master/controllers/front/snappay.php#L51](https://github.com/veritrans/SNAP-Prestashop/blob/master/controllers/front/snappay.php#L51) call the `snappay.tpl` partial into the views.

So i delete the contents in `snappay.tpl` file, but nothings changed. It is still works (the page show correctly with snap).

**Comment by rizdaprasetya** [comment]
> So i delete the contents in snappay.tpl file, but nothings changed. It is still works (the page show correctly with snap).

Prestashop like to keep internal cache of TPL files, so maybe that's why even after TPL is changed or deleted it keep displaying the old page from cache.

You should not use vtweb module because it no longer maintained.
I try to made a fix:
https://github.com/veritrans/SNAP-Prestashop/commit/008493f83f17c4685949665b62e1547c3fd42ef4

You can try to redownload and install this module again. (Also uninstall the vtweb plugin first)

**Comment by rizdaprasetya** [comment]
This issue has been solved on 13/04/18 but will be kept open for a while, just incase other users face the same issue.
